### ISSUE TITLE
What delivery mechanisms are we required to accomodate?

### ISSUE THREAD

**Issue by mrsgit09** [OfficeCompliance/vNext-Investigations#5]
- [ ] MSDN Style
- [ ] PDF
- [ ] DOC/DOCX

***
Constraint
	Docs must be available on MSDN (API Style)
	
Real or Perceived Requirement/Benefit?
	It is likely more a perception than absolute reality born from the following:
	From <https://msdn.microsoft.com/en-us/openspecifications/dn646764> 
	
	Interoperability Principles Program
	In connection with the Interoperability Principles, announced February 21, 2008, Microsoft also makes available additional technical specifications for protocols in its high-volume products: Windows Vista (including .NET Framework), Windows Server 2008, Microsoft Office 2007, Microsoft Office SharePoint Server 2007, Exchange Server 2007, Microsoft SQL Server 2008, and future versions of each of these products.
	These specifications are published and available on MSDN at no charge (rights under Microsoft patents covering such specifications are available separately).
	
	* Neither the Warranty Agreement nor the Public Undertaking specifically mentions MSDN.  
	* The Samba Warranty does mention MSDN.
	
Is Removing or Modifying the Constraint a Possibility?
	
	From <https://msdn.microsoft.com/en-us/openspecifications/dn646764> 
	At the bottom of the Interoperability Principles Program page it says:
	
	These promises apply individually to each of these specifications:
	"Open Specifications" (as published at http://msdn.microsoft.com/en-us/library/dd208104.aspx or its successor site) for the protocols implemented in the current and future versions of Windows Vista including the .NET Framework, Windows Server 2008, SQL Server 2008, Office 2007, Exchange 2007, and Office SharePoint Server 2007, that are used by any other Microsoft product to connect with these products.

**Comment by skesseks** [comment]
Will we still require the templates and need to format the 'documents' ?

**Comment by mrsgit09** [comment]
Need to investigate.
